package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String idClient;
     private String nomClient;
     private String prenomClient;
     private String adresseClient;
     private Long cpClient;
     private String villeClient;
     private String telClient;
     private String emailClient;
     private Set<Facture> factures = new HashSet<Facture>(0);

    public Client() {
    }

	
    public Client(String idClient) {
        this.idClient = idClient;
    }
    public Client(String idClient, String nomClient, String prenomClient, String adresseClient, Long cpClient, String villeClient, String telClient, String emailClient, Set<Facture> factures) {
       this.idClient = idClient;
       this.nomClient = nomClient;
       this.prenomClient = prenomClient;
       this.adresseClient = adresseClient;
       this.cpClient = cpClient;
       this.villeClient = villeClient;
       this.telClient = telClient;
       this.emailClient = emailClient;
       this.factures = factures;
    }
   
    public String getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(String idClient) {
        this.idClient = idClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }
    
    public void setPrenomClient(String prenomClient) {
        this.prenomClient = prenomClient;
    }
    public String getAdresseClient() {
        return this.adresseClient;
    }
    
    public void setAdresseClient(String adresseClient) {
        this.adresseClient = adresseClient;
    }
    public Long getCpClient() {
        return this.cpClient;
    }
    
    public void setCpClient(Long cpClient) {
        this.cpClient = cpClient;
    }
    public String getVilleClient() {
        return this.villeClient;
    }
    
    public void setVilleClient(String villeClient) {
        this.villeClient = villeClient;
    }
    public String getTelClient() {
        return this.telClient;
    }
    
    public void setTelClient(String telClient) {
        this.telClient = telClient;
    }
    public String getEmailClient() {
        return this.emailClient;
    }
    
    public void setEmailClient(String emailClient) {
        this.emailClient = emailClient;
    }
    public Set<Facture> getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }




}


