package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA



/**
 * Contient generated by hbm2java
 */
public class Contient  implements java.io.Serializable {


     private ContientId id;
     private Produit produit;
     private Facture facture;
     private String qteProduitFacturee;

    public Contient() {
    }

	
    public Contient(ContientId id, Produit produit, Facture facture) {
        this.id = id;
        this.produit = produit;
        this.facture = facture;
    }
    public Contient(ContientId id, Produit produit, Facture facture, String qteProduitFacturee) {
       this.id = id;
       this.produit = produit;
       this.facture = facture;
       this.qteProduitFacturee = qteProduitFacturee;
    }
   
    public ContientId getId() {
        return this.id;
    }
    
    public void setId(ContientId id) {
        this.id = id;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Facture getFacture() {
        return this.facture;
    }
    
    public void setFacture(Facture facture) {
        this.facture = facture;
    }
    public String getQteProduitFacturee() {
        return this.qteProduitFacturee;
    }
    
    public void setQteProduitFacturee(String qteProduitFacturee) {
        this.qteProduitFacturee = qteProduitFacturee;
    }




}


