package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA



/**
 * ContientId generated by hbm2java
 */
public class ContientId  implements java.io.Serializable {


     private String idFacture;
     private String idProduit;

    public ContientId() {
    }

    public ContientId(String idFacture, String idProduit) {
       this.idFacture = idFacture;
       this.idProduit = idProduit;
    }
   
    public String getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(String idFacture) {
        this.idFacture = idFacture;
    }
    public String getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(String idProduit) {
        this.idProduit = idProduit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContientId) ) return false;
		 ContientId castOther = ( ContientId ) other; 
         
		 return ( (this.getIdFacture()==castOther.getIdFacture()) || ( this.getIdFacture()!=null && castOther.getIdFacture()!=null && this.getIdFacture().equals(castOther.getIdFacture()) ) )
 && ( (this.getIdProduit()==castOther.getIdProduit()) || ( this.getIdProduit()!=null && castOther.getIdProduit()!=null && this.getIdProduit().equals(castOther.getIdProduit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdFacture() == null ? 0 : this.getIdFacture().hashCode() );
         result = 37 * result + ( getIdProduit() == null ? 0 : this.getIdProduit().hashCode() );
         return result;
   }   


}


