package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private String idFacture;
     private Utilisateur utilisateur;
     private Client client;
     private Date dateFacture;
     private Double montantFacture;
     private String modePaiementFacture;
     private Set<Contient> contients = new HashSet<Contient>(0);

    public Facture() {
    }

	
    public Facture(String idFacture, Utilisateur utilisateur, Client client) {
        this.idFacture = idFacture;
        this.utilisateur = utilisateur;
        this.client = client;
    }
    public Facture(String idFacture, Utilisateur utilisateur, Client client, Date dateFacture, Double montantFacture, String modePaiementFacture, Set<Contient> contients) {
       this.idFacture = idFacture;
       this.utilisateur = utilisateur;
       this.client = client;
       this.dateFacture = dateFacture;
       this.montantFacture = montantFacture;
       this.modePaiementFacture = modePaiementFacture;
       this.contients = contients;
    }
   
    public String getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(String idFacture) {
        this.idFacture = idFacture;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDateFacture() {
        return this.dateFacture;
    }
    
    public void setDateFacture(Date dateFacture) {
        this.dateFacture = dateFacture;
    }
    public Double getMontantFacture() {
        return this.montantFacture;
    }
    
    public void setMontantFacture(Double montantFacture) {
        this.montantFacture = montantFacture;
    }
    public String getModePaiementFacture() {
        return this.modePaiementFacture;
    }
    
    public void setModePaiementFacture(String modePaiementFacture) {
        this.modePaiementFacture = modePaiementFacture;
    }
    public Set<Contient> getContients() {
        return this.contients;
    }
    
    public void setContients(Set<Contient> contients) {
        this.contients = contients;
    }




}


