package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur  implements java.io.Serializable {


     private String idFournisseur;
     private String nomFournisseur;
     private String coordonnees;
     private Set<Stockproduit> stockproduits = new HashSet<Stockproduit>(0);

    public Fournisseur() {
    }

	
    public Fournisseur(String idFournisseur) {
        this.idFournisseur = idFournisseur;
    }
    public Fournisseur(String idFournisseur, String nomFournisseur, String coordonnees, Set<Stockproduit> stockproduits) {
       this.idFournisseur = idFournisseur;
       this.nomFournisseur = nomFournisseur;
       this.coordonnees = coordonnees;
       this.stockproduits = stockproduits;
    }
   
    public String getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(String idFournisseur) {
        this.idFournisseur = idFournisseur;
    }
    public String getNomFournisseur() {
        return this.nomFournisseur;
    }
    
    public void setNomFournisseur(String nomFournisseur) {
        this.nomFournisseur = nomFournisseur;
    }
    public String getCoordonnees() {
        return this.coordonnees;
    }
    
    public void setCoordonnees(String coordonnees) {
        this.coordonnees = coordonnees;
    }
    public Set<Stockproduit> getStockproduits() {
        return this.stockproduits;
    }
    
    public void setStockproduits(Set<Stockproduit> stockproduits) {
        this.stockproduits = stockproduits;
    }




}


