package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Prixproduit generated by hbm2java
 */
public class Prixproduit  implements java.io.Serializable {


     private String idPrix;
     private Produit produit;
     private Date debutValiditePrix;
     private Date finValiditePrix;
     private Double valeurPrix;

    public Prixproduit() {
    }

	
    public Prixproduit(String idPrix, Produit produit) {
        this.idPrix = idPrix;
        this.produit = produit;
    }
    public Prixproduit(String idPrix, Produit produit, Date debutValiditePrix, Date finValiditePrix, Double valeurPrix) {
       this.idPrix = idPrix;
       this.produit = produit;
       this.debutValiditePrix = debutValiditePrix;
       this.finValiditePrix = finValiditePrix;
       this.valeurPrix = valeurPrix;
    }
   
    public String getIdPrix() {
        return this.idPrix;
    }
    
    public void setIdPrix(String idPrix) {
        this.idPrix = idPrix;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Date getDebutValiditePrix() {
        return this.debutValiditePrix;
    }
    
    public void setDebutValiditePrix(Date debutValiditePrix) {
        this.debutValiditePrix = debutValiditePrix;
    }
    public Date getFinValiditePrix() {
        return this.finValiditePrix;
    }
    
    public void setFinValiditePrix(Date finValiditePrix) {
        this.finValiditePrix = finValiditePrix;
    }
    public Double getValeurPrix() {
        return this.valeurPrix;
    }
    
    public void setValeurPrix(Double valeurPrix) {
        this.valeurPrix = valeurPrix;
    }




}


