package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private String idProduit;
     private String nomProduit;
     private String garantieProduit;
     private Set<Prixproduit> prixproduits = new HashSet<Prixproduit>(0);
     private Set<Stockproduit> stockproduits = new HashSet<Stockproduit>(0);
     private Set<Contient> contients = new HashSet<Contient>(0);

    public Produit() {
    }

	
    public Produit(String idProduit) {
        this.idProduit = idProduit;
    }
    public Produit(String idProduit, String nomProduit, String garantieProduit, Set<Prixproduit> prixproduits, Set<Stockproduit> stockproduits, Set<Contient> contients) {
       this.idProduit = idProduit;
       this.nomProduit = nomProduit;
       this.garantieProduit = garantieProduit;
       this.prixproduits = prixproduits;
       this.stockproduits = stockproduits;
       this.contients = contients;
    }
   
    public String getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(String idProduit) {
        this.idProduit = idProduit;
    }
    public String getNomProduit() {
        return this.nomProduit;
    }
    
    public void setNomProduit(String nomProduit) {
        this.nomProduit = nomProduit;
    }
    public String getGarantieProduit() {
        return this.garantieProduit;
    }
    
    public void setGarantieProduit(String garantieProduit) {
        this.garantieProduit = garantieProduit;
    }
    public Set<Prixproduit> getPrixproduits() {
        return this.prixproduits;
    }
    
    public void setPrixproduits(Set<Prixproduit> prixproduits) {
        this.prixproduits = prixproduits;
    }
    public Set<Stockproduit> getStockproduits() {
        return this.stockproduits;
    }
    
    public void setStockproduits(Set<Stockproduit> stockproduits) {
        this.stockproduits = stockproduits;
    }
    public Set<Contient> getContients() {
        return this.contients;
    }
    
    public void setContients(Set<Contient> contients) {
        this.contients = contients;
    }




}


