package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA



/**
 * Stockproduit generated by hbm2java
 */
public class Stockproduit  implements java.io.Serializable {


     private String idStockProduit;
     private Fournisseur fournisseur;
     private Utilisateur utilisateur;
     private Produit produit;
     private String qteProduitStocke;

    public Stockproduit() {
    }

	
    public Stockproduit(String idStockProduit, Fournisseur fournisseur, Utilisateur utilisateur, Produit produit) {
        this.idStockProduit = idStockProduit;
        this.fournisseur = fournisseur;
        this.utilisateur = utilisateur;
        this.produit = produit;
    }
    public Stockproduit(String idStockProduit, Fournisseur fournisseur, Utilisateur utilisateur, Produit produit, String qteProduitStocke) {
       this.idStockProduit = idStockProduit;
       this.fournisseur = fournisseur;
       this.utilisateur = utilisateur;
       this.produit = produit;
       this.qteProduitStocke = qteProduitStocke;
    }
   
    public String getIdStockProduit() {
        return this.idStockProduit;
    }
    
    public void setIdStockProduit(String idStockProduit) {
        this.idStockProduit = idStockProduit;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public String getQteProduitStocke() {
        return this.qteProduitStocke;
    }
    
    public void setQteProduitStocke(String qteProduitStocke) {
        this.qteProduitStocke = qteProduitStocke;
    }




}


