package modele;
// Generated 11 mai 2013 15:07:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String idUser;
     private String nomUser;
     private String prenomUser;
     private String fonctionUser;
     private String loginUser;
     private String mdpUser;
     private Set<Stockproduit> stockproduits = new HashSet<Stockproduit>(0);
     private Set<Facture> factures = new HashSet<Facture>(0);

    public Utilisateur() {
    }

	
    public Utilisateur(String idUser) {
        this.idUser = idUser;
    }
    public Utilisateur(String idUser, String nomUser, String prenomUser, String fonctionUser, String loginUser, String mdpUser, Set<Stockproduit> stockproduits, Set<Facture> factures) {
       this.idUser = idUser;
       this.nomUser = nomUser;
       this.prenomUser = prenomUser;
       this.fonctionUser = fonctionUser;
       this.loginUser = loginUser;
       this.mdpUser = mdpUser;
       this.stockproduits = stockproduits;
       this.factures = factures;
    }
   
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    public String getNomUser() {
        return this.nomUser;
    }
    
    public void setNomUser(String nomUser) {
        this.nomUser = nomUser;
    }
    public String getPrenomUser() {
        return this.prenomUser;
    }
    
    public void setPrenomUser(String prenomUser) {
        this.prenomUser = prenomUser;
    }
    public String getFonctionUser() {
        return this.fonctionUser;
    }
    
    public void setFonctionUser(String fonctionUser) {
        this.fonctionUser = fonctionUser;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getMdpUser() {
        return this.mdpUser;
    }
    
    public void setMdpUser(String mdpUser) {
        this.mdpUser = mdpUser;
    }
    public Set<Stockproduit> getStockproduits() {
        return this.stockproduits;
    }
    
    public void setStockproduits(Set<Stockproduit> stockproduits) {
        this.stockproduits = stockproduits;
    }
    public Set<Facture> getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }




}


